version: "3.4"
services:
  squid:
    ports:
      - 3128:3128
    image: b4tman/squid:5.3
    volumes:
      - './config:/etc/squid/conf.d:ro'
    container_name: dockersquid_rotate
    environment:
      - 'SQUID_CONFIG_FILE=/etc/squid/conf.d/squid.conf'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD-SHELL", "export https_proxy=127.0.0.1:3128 && export http_proxy=127.0.0.1:3128 && wget -q -Y on  -O - https://checkip.amazonaws.com || exit 1" ]
      retries: 5
      timeout: "10s"
      start_period: "10s"
      interval: "300s"
