version: "3.3"
services:
  squid:
    ports:
      - 3128:3128
    image: b4tman/squid:5.3
    volumes:
      - './config:/etc/squid/conf.d:ro'
    container_name: dockersquid_rotate
    environment:
      - 'SQUID_CONFIG_FILE=/etc/squid/conf.d/squid.conf'
    extra_hosts:
      - "host.docker.internal:host-gateway"